website/views/auth.py
from flask import Blueprint, render_template, request, url_for, flash,redirect, current_app
from datetime import datetime
# from website.token import generate_confirmation_token, confirm_token
from website.views.forms import RegistrationForm, LoginForm, RequestResetForm, ResetPasswordForm
from website.app import db
from website.models import User
from flask_login import login_user, current_user, logout_user, login_required
from website.app import bcrypt, login_manager
from website.email import send_reset_email, send_mail_confirmation
from .search import history_get, history_delete
from ..models import History, Product as ProductModel, load_user
from sqlalchemy import select, update
from os import path

auth = Blueprint('auth', __name__)



@auth.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            if user.confirmed:
                login_user(user, remember=form.remember.data)
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('views.home'))
            else:
                flash('Check your mail associated with this account to confirm the account.', 'info')
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template("login.html", form=form)


@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('views.home'))


@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(firstName=form.firstName.data, lastName=form.lastName.data, email=form.email.data, password=hashed_password, registered_on=datetime.now())
        db.session.add(user)
        db.session.commit()
        send_mail_confirmation(user)
        flash(f'Account created for {form.firstName.data}!  Please chceck your email for verification!','success')
        return redirect(url_for('auth.login'))
    return render_template('signup.html',form=form)

@auth.route('/account', methods=('GET', 'POST'))
@login_required
def account():
    DEFAULT_IMAGE = 'default.jpg'
    # Prepare account data
    user = load_user(current_user.id)
    user.registered_on = user.registered_on.date()
    image_path = path.join(url_for('static', filename='img'), user.imag_file)
    image_path = path.join(current_app.root_path, image_path.strip('/'))
    if not path.isfile(image_path):
        # Profile image does not exits change it to the default one
        stmt = update(User).where(User.id == current_user.id).values(imag_file = DEFAULT_IMAGE)
        db.session.execute(stmt)
        db.session.commit()
        user.imag_file = DEFAULT_IMAGE
    # Prepare history data
    history_data, _ = history_get()
    history_data = history_data.get_json()
    for product_history in history_data:
        stmt = select(ProductModel).where(ProductModel.history_id == product_history['history_id'])
        products_model = db.session.execute(stmt)
        products = [prod[0] for prod in products_model.fetchall()]
        product_list = list()
        for product_list_item in product_history['products_list']:
            product_name = product_list_item.split(':')[1].strip(' ')
            product_url = '#'
            for product in products:
                if product.name == product_name:
                    product_url = product.url
                    break
            product_list.append(
                {
                    'product_name': product_name,
                    'product_url': product_url,
                }
            )
        product_history['products_list'] = product_list
        product_history['product_url'] = product_url
        product_history['search_date'] = product_history['search_date'].replace(' GMT','')
        product_history['products_list'] = product_list
    search_btn_id = request.args.get('history-btn', None)
    if search_btn_id is not None:
        history_delete(search_btn_id)
        return redirect(url_for('auth.account'))
    if request.method == 'POST':
        image = request.files.get('image', None)
        if image.filename == '':
            flash('No file selected', 'danger')
            return redirect(url_for('auth.account'))
        image_name = str(user.id) + path.splitext(image.filename)[1]
        image_path = path.join(url_for('static', filename='img'), image_name)
        image_path = path.join(current_app.root_path, image_path.strip('/'))
        image.save(image_path)
        stmt = update(User).where(User.id == current_user.id).values(imag_file = image_name)
        db.session.execute(stmt)
        db.session.commit()
        user.image_file = image_name
        return redirect(url_for('auth.account'))
    return render_template('account.html',history_data=history_data, user=user)

@auth.route('/reset_password', methods=['GET','POST'])
def reset_request():
    if current_user.is_authenticated:
        user = User.query.filter_by(id=current_user.id).first()
        send_reset_email(user)
        logout_user()
        flash('An email has been sent with instructions to reset your password.','info')
        return redirect(url_for('auth.login'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.','info')
        return redirect(url_for('auth.login'))
    return render_template('reset_request.html', form=form)

@auth.route('/reset_password/<token>', methods=['GET','POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('auth.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been update! You are now able to log in.','success')
        return redirect(url_for('auth.login'))
    return render_template('reset_token.html', form=form)

@auth.route('/confirm_email/<token>', methods=['GET','POST'])
def confirm_email(token):
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    email = User.verify_mail_confirm_token(token)
    if email:
        user = db.session.query(User).filter(User.email == email).one_or_none()
        user.confirmed =True
        user.confirmed_on=datetime.now()
        db.session.add(user)
        db.session.commit()
        flash(f"Your email has been verified and you can now login to your account","success",)
        return redirect(url_for('auth.login'))
    else:
        flash('The confirmation link is invalid or has expired.', 'warning')
        return redirect(url_for('auth.signup'))

website/views/views.py
from flask import Blueprint, render_template

views = Blueprint('views', __name__)


@views.route('/')
def home():
    return render_template('home.html')


@views.route("/results/<token>")
def results(token):
    return render_template('results.html')


@views.route("/results_db/<history_id>")
def results_db(history_id):
    return render_template('results.html')

website/templates/account.html
{% extends "base.html" %}
{% block title %}Account{% endblock %}
{% block content %}

<div class="container-sm text-center" style="color: #FFFFFF; width: 85%; margin-top: 2vh">

  <!-- User Info Card-->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <form method="POST" action="" enctype="multipart/form-data">
          <div class="modal-header">
            <label class="form-label" for="customFile">Load Image</label>
            <input name="image" type="file" class="form-control" id="customFile" accept=".jpg,.png" />
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save changes</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="card rounded-lg" style="background-color:#5200cc; border-radius: 25px;">
    <div class="container py-5">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-6 mb-4 mb-lg-0">
          <div class="card mb-3" style="border-radius: .5rem;">
            <div class="row g-0">
              <div class="col-md-4 gradient-custom text-center text-white"
                style="border-top-left-radius: .5rem; border-bottom-left-radius: .5rem;">
                {% set image_path = 'img/' + user.imag_file %}
                <img src="{{url_for('static', filename = image_path)}}" alt="Avatar" class="img-fluid my-5"
                  style="width: 80px;" />
                <h5 class="account-primary-text">{{user.firstName}}</h5>
                <small>Registered on</small>
                <br>
                <small>{{ user.registered_on }}</small>
                <i class="far fa-edit mb-5"></i>
              </div>
              <div class="col-md-8">
                <div class="card-body p-4">
                  <div class="row pt-1">
                    <div class="col mb-3">
                      <h6 class="account-info-text">Email</h6>
                      <p class="text-muted">{{user.email}}</p>
                    </div>
                  </div>
                  <div class="row pt-1">
                    <div class="col mb-3">
                      <h6 class="account-info-text">Full Name</h6>
                      <p class="text-muted">{{user.firstName}} {{user.lastName}}</p>
                    </div>
                  </div>
                  <div class="d-flex justify-content-start">
                    <a href="{{ url_for('auth.reset_request') }}"
                      class="fab fa-facebook-f fa-lg me-3 btn btn-primary">Change Password</a>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Change
                      Profile Image</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- card header-->
    <div class="card-body ">
      <h3>Search History</h3>
    </div>
    <!-- card body-->
    <div class="card-body">
      <!-- list of products-->
      {% if history_data %}
      <div id="divHistoryList" class="card rounded-lg p-3" style="background-color: #FFFFFF; border-radius: 25px;">
        <ul class="list-group">
          <div id="accordion">
            {% for product_history in history_data %}
            <div class="card">
              <div class="card-header" id="heading{{ product_history['history_id'] }}">
                <div class="container">
                  <div class="row">
                    <div class="col-9">
                      <h5 class="mb-0 text-primary">
                        <button class="btn collapsed" data-toggle="collapse"
                          data-target="#collapse{{ product_history['history_id'] }}" aria-expanded="true"
                          aria-controls="collapseOne">
                          {{ product_history['search_date'] }}
                        </button>
                      </h5>
                    </div>
                    <div class="col-3 d-flex justify-content-end">
                      <form id="search-history-form" method="GET">
                        <a href="{{ url_for('views.results_db', history_id=product_history['history_id'])}}" class="btn btn-primary" role="button">Details</a>

                        <button class="btn btn-danger" type="submit" name="history-btn"
                          value="{{ product_history['history_id'] }}">Delete</button>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
              <div id="collapse{{ product_history['history_id'] }}" class="collapse"
                aria-labelledby="heading{{ product_history['history_id'] }}" data-parent="#accordion">
                <div class="card-body">
                  {% for product in product_history['products_list'] %}
                  <div class="row">
                    <div class="col-9">
                    <a class="link-primary" target="_blank" href="{{product['product_url']}}">{{ product['product_name'] }}</a>
                  </div>
                  </div>
                  {% endfor %}
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </ul>
      </div>
      {% else %}
      <div class="card rounded-lg" style="background-color: white; border-radius: 25px;">
        <strong style="color: #5200cc;">( Empty )</strong>
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}


{% block scripts %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
  integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="../static/css/styles.css">
  <link rel="stylesheet" href="../static/css/home.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
  <title>{% block title %}Home{% endblock %}</title>
</head>

<body>

  <!--background-->
  <div class="area" style="position: fixed; top:0; z-index: -1">
    <!--floating circles -->
    <ul class="circles">
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
    </ul>


  </div> <!--end background-->

  <!-- navbar-->
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#3A3ACB;">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <li class="nav-item">
              <a class="nav-item nav-link text-white" id="home" href="{{ url_for('views.home') }}"><img
                  src="./../static/img/icons8-home-32.png"><br>Home</a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-item nav-link text-white" id="account" href="{{ url_for('auth.account') }}"><img
                  src="./../static/img/icons8-user-male-32.png"><br>Account</a>
            </li>
            <li class="nav-item">
              <a class="nav-item nav-link text-white" id="logout" href="{{ url_for('auth.logout') }}"><img
                  src="./../static/img/icons8-close-32.png"><br>Log out</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-item nav-link text-white" id="login" href="{{ url_for('auth.login') }}"><img
                  src="./../static/img/icons8-check-all-32.png"><br>Log in</a>
            </li>
            <li class="nav-item">
              <a class="nav-item nav-link text-white" id="signUp" href="{{ url_for('auth.signup') }}"><img
                  src="./../static/img/icons8-key-32.png"><br>Sign Up</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <main class="container" style="margin-top: 4vh">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    <br>
    {% block content %}{% endblock %}
  </main>

  <div style="min-height: 100px;"></div>

  <footer class="bg-light text-center text-white" style="margin-top: 5vh; position: fixed; bottom: 0vh; width: 100%;">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: #3A3ACB;">
      © 2022 Copyright:
      <a class="text-white" href="https://github.com/nieckojakub/IOProject">Github.com</a>
    </div>
    <!-- Copyright -->
  </footer>


</body>
<script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI="
  crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
  integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"
  integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>

{% block scripts %}{% endblock %}


</html>

website/templates/confirm_email.html
<!doctype html>
<html lang="en-US">

<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
    <title>Confirm Password</title>
    <meta name="description" content="Reset Password Email Template.">
    <style type="text/css">
        a:hover {text-decoration: underline !important;}
    </style>
</head>

<body marginheight="0" topmargin="0" marginwidth="0" style="margin: 0px; background-color: #f2f3f8;" leftmargin="0">
    <!--100% body table-->
    <table cellspacing="0" border="0" cellpadding="0" width="100%" bgcolor="#f2f3f8"
        style="@import url(https://fonts.googleapis.com/css?family=Rubik:300,400,500,700|Open+Sans:300,400,600,700); font-family: 'Open Sans', sans-serif;">
        <tr>
            <td>
                <table style="background-color: #f2f3f8; max-width:670px;  margin:0 auto;" width="100%" border="0"
                    align="center" cellpadding="0" cellspacing="0">
                    <tr>
                        <td style="height:80px;">&nbsp;</td>
                    </tr>
                    <tr>
                    </tr>
                    <tr>
                        <td style="height:20px;">&nbsp;</td>
                    </tr>
                    <tr>
                        <td>
                            <table width="95%" border="0" align="center" cellpadding="0" cellspacing="0"
                                style="max-width:670px;background:#fff; border-radius:3px; text-align:center;-webkit-box-shadow:0 6px 18px 0 rgba(0,0,0,.06);-moz-box-shadow:0 6px 18px 0 rgba(0,0,0,.06);box-shadow:0 6px 18px 0 rgba(0,0,0,.06);">
                                <tr>
                                    <td style="height:40px;">&nbsp;</td>
                                </tr>
                                <tr>
                                    <td style="padding:0 35px;">
                                        <h1 style="color:#1e1e2d; font-weight:500; margin:0;font-size:32px;font-family:'Rubik',sans-serif;">Thank you for joining AlCen Helper!</h1>
                                        <span
                                            style="display:inline-block; vertical-align:middle; margin:29px 0 26px; border-bottom:1px solid #cecece; width:100px;"></span>
                                        <p style="color:#455056; font-size:15px;line-height:24px; margin:0;">
                                           Click the following link or button to verify your email

                                        </p>
                                        <a href="{ url_for('auth.confirm_email', token=token, _external=True) }"
                                            style="background:#20e277;text-decoration:none !important; font-weight:500; margin-top:35px; color:#fff;text-transform:uppercase; font-size:14px;padding:10px 24px;display:inline-block;border-radius:50px;">Reset
                                            Password</a>

                                         <p style="color:#455056; font-size:15px;line-height:24px; margin:0;">
                                            If button is not working click this link: { url_for('auth.confirm_email', token=token, _external=True) }

                                        </p>
                                        <p>


                                            If you didn't create an account with AlCen Helper, you can safely delete this email.
                                            <br><br>
                                            Sincerely,
                                            AlCen Helper Team
                                        </p>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="height:40px;">&nbsp;</td>
                                </tr>
                            </table>
                        </td>
                    <tr>
                        <td style="height:20px;">&nbsp;</td>
                    </tr>
                    <tr>
                        <td style="text-align:center;">
                            <a href="{{ url_for('views.home') }}">
                                <p style="font-size:14px; color:rgba(69, 80, 86, 0.7411764705882353); line-height:18px; margin:0 0 0;">&copy; <strong>www.AlCen Helper.com</strong></p>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td style="height:80px;">&nbsp;</td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <!--/100% body table-->
</body>

</html>

website/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Your search overview</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"
                    onclick="restartToken()"></button>
            </div>
            <div class="modal-body">
                <div id="progresbarDiv" style="width:100%;">
                    <div id="progressbar" style="width:0%; background-color:green; height:10px"></div>
                </div>
                <div>
                    <table id="modalSearchOverviewTable">
                        <thead>
                            <tr>
                                <th>Product Name</th>
                                <th>Search Status</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
                <div id="modalSearchBtn">
                    <button type="button" class="btn btn-success
                    mt-2" onclick="sendProducts();" style="width: 100%">Search</button>
                </div>
                <div id="modalResultsBtn" style="display: none; text-align: center;">
                    <button type="button" class="btn btn-success
                    mt-2" onclick="goToResults();" style="width: 100%">Show Results</button>
                    <h5 style="display: inline;">Your search took: <h5 style="display: inline;" id="timeSummar"></h5>
                    </h5>
                </div>

                <div id="modalSearchText" style="display: none; width: 100%">
                    Searching...
                    <p id="timer" style="display: inline; float: right;"></p>
                </div>

                <div id="modalPartialResultsBtn" style="display: none;">
                    <button type="button" class="btn btn-success
                    mt-2" onclick="ensurePartialResults();" style="width: 100%">Show partial results</button>
                </div>

                <div id="ensureDiv" style="display: none; width: 100%">
                    <b>Are you sure You want to see only partial results?</b>
                    <button type="button" class="btn btn-success
                    mt-2" onclick="goToResults();" style="display: inline; " id="ensurePositive">Go to results
                        page</button>
                    <button type="button" class="btn btn-danger
                    mt-2" onclick="negativeEnsure();" style="display: inline; " id="ensureNegative">Continue
                        searching</button>
                </div>


            </div>
        </div>
    </div>
</div>


<!-- Info Modal -->
<div class="modal fade" id="infoModal" tabindex="-1" aria-labelledby="infoModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="infoModalLabel">Warning!</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" style="display: grid; place-items: center;">
                <h3 id="infoInModal"></h3>
            </div>
        </div>
    </div>
</div>

<!--Info button trigger-->
<button id="trigerInfoModal" type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#infoModal"
    style="display:none">
</button>


<div class="container-sm text-center" style="color: #FFFFFF; width: 85%; margin-top: 2vh">

    <!-- login card-->
    <div class="card rounded-lg" style="background-color:#5200cc; border-radius: 25px;">

        <!-- card header-->
        <div class="card-body ">
            {% if current_user.is_authenticated %}
            <b> CenAll </b>
            <h4 class="card-title">Hello {{ current_user.firstName }}, we are happy to see You!</h4>
            {% else %}
            <h4 class="card-title">Good luck searching!</h4>
            {% endif %}
        </div>


        <!-- card body-->
        <div class="card-body">
            <!-- Button trigger modal -->
            <button id="trigerProgresBar" type="button" class="btn btn-primary" data-bs-toggle="modal"
                data-bs-target="#staticBackdrop" style="display:none">
            </button>
            <form>
                <!-- check boxes-->
                <h6 style="display: inline">Please, select the source of Your search:</h6>
                <!-- Allegro-->
                <div style="display: inline; margin-left: 20px">
                    <input class="form-check-input" type="checkbox" id="AllegroCheckbox" value="Allegro">
                    <label class="form-check-label" for="AllegroCheckbox">Allegro</label>
                </div>
                <!-- Ceneo-->
                <div style="display: inline; margin-left: 20px">
                    <input class="form-check-input" type="checkbox" id="CeneoCheckbox" value="Ceneo" checked>
                    <label class="form-check-label" for="CeneoCheckbox">Ceneo</label>
                </div>
                <!-- Search input + add button + quantity form + read from file -->
                <div class="mb-3 row">
                    <div class="col-8">
                        <input type="text" class="form-control mt-2" id="SearchInput" aria-describedby="SearchHelp">
                    </div>
                    <div class="col-auto mt-2">

                        <div class="input-group" style="max-width: 127px;">
                            <button id="minusButtonMain" class="btn btn-danger" type="button" style="display:inline"
                                onclick="return minusBtn(this);">-</button>
                            <input id="amountMain" type="text" class="form-control" value="1" min="1" max="10"
                                style="display:inline; max-width: 45px;" onchange="return validateAmount(this);">
                            <button id="plusButtonMain" class="btn btn-success" type="button" style="display:inline"
                                onclick="return plusBtn(this);">+</button>
                        </div>

                    </div>
                    <div class="col-auto">
                        <button type="button" id="AddButton" class="btn btn-primary mt-2"
                            onclick="addProduct()">Add</button>
                    </div>
                    <div class="col-auto">
                        <form>
                            <input type="file" id="addFromFileInput" accept=".txt" style="display: none;"
                                onchange="return readFromFile(event);"></input>
                            <button type="button" id="addFromFileButton" class="btn btn-primary mt-2"
                                onclick="document.getElementById('addFromFileInput').click()">From File</button>
                        </form>
                    </div>

                </div>
                <div id="SearchHelp" class="form-text" style="color: white;"></div>

            </form>

            <!-- list of products-->
            <div class="card rounded-lg" id="divListOfProducts" style="background-color:#ffffff; border-radius: 25px;">
                <div id="ListOfProducts" class="card-body" style="color:#000000;">

                </div>
            </div>

            <!-- submit button-->
            <div class="container" style="display:inline">
                <button type="button" id="SubmitBtn" class="btn btn-success mt-2" onclick="showModal();">Submit</button>
            </div>
        </div>

        <div style="height: 15px;" class="card-footer"></div>

    </div>

</div>

<script src="../static/js/home_scripts.js"></script>

{% endblock %}

website/templates/logout.html
{% extends "base.html" %}
{% block title %}Logout{% endblock %}
{% block content %}

Logout html
{% endblock %}